src/HospitalManagement/Controllers/AdminController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using HospitalManagement.Models;
using Microsoft.AspNet.Authorization;
using HospitalManagement.ViewModels.Admin;
using Microsoft.AspNet.Http;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Net.Http.Headers;
using Microsoft.Extensions.PlatformAbstractions;
using Microsoft.AspNet.Hosting;

namespace HospitalManagement.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext _context;
        private IApplicationEnvironment _hostingEnvironment;


        public AdminController(ApplicationDbContext context, IApplicationEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;

        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult AddPatientPage()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPatient(PatientViewModel model, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                ModifyPatient m = new ModifyPatient(_context);
                await m.addPatient(model.Fname, model.Lname,model.Email, model.Gender, model.PatientAge, model.BloodGroup, model.ContactNo, model.Address, model.PatientDetails, model.PatientHistory, model.DoctorDiagnosis, model.Comments, model.Email + ".jpg");
                var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                if (fileName.EndsWith(".jpg") || fileName.EndsWith(".png") || fileName.EndsWith(".jpeg") || fileName.EndsWith(".gif") || fileName.EndsWith(".bmp") || fileName.EndsWith(".tiff"))

                {

                    var filePath = _hostingEnvironment.ApplicationBasePath + "\\wwwroot\\profiledat\\" + model.Email + ".jpg";
                    await file.SaveAsAsync(filePath);

                }



                return RedirectToAction("Home");


            }

            return View("AddPatientPage", model);


        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ModifyPatientPage()
        {

            GetPatient getPatient = new GetPatient(_context);
            List<Patient> patients = getPatient.getAllPatients();


            return View(patients);
        }
        
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Home()
        {
            User user = new User();
            user.Email = HttpContext.Session.GetString("Email");
            user.Fname = HttpContext.Session.GetString("FName");

            return View(user);
        }

        
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePatients(IEnumerable<int> PatientsToDeleteCheckboxes)
        {

            if (PatientsToDeleteCheckboxes.Count<int>() != 0)
            {
                ModifyPatient mP = new ModifyPatient(_context);


                foreach (var p in PatientsToDeleteCheckboxes)
                {
                    await mP.deletePatient(p);

                }


            }

           
           


          return RedirectToAction("ModifyPatientPage");


        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SavePatientChanges(PatientViewModel model, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                ModifyPatient m = new ModifyPatient(_context);
                int count = 0;
                if (file != null)
                    count = 1;

                await m.updatePatient(int.Parse( HttpContext.Session.GetString("PatientId")), model,count);

                if(file!=null)
                {
                    var fullPath = _hostingEnvironment.ApplicationBasePath + "\\wwwroot\\profiledat\\" + model.Email + ".jpg";
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }


                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                    if (fileName.EndsWith(".jpg") || fileName.EndsWith(".png") || fileName.EndsWith(".jpeg") || fileName.EndsWith(".gif") || fileName.EndsWith(".bmp") || fileName.EndsWith(".tiff"))

                    {

                       var filePath = _hostingEnvironment.ApplicationBasePath + "\\wwwroot\\profiledat\\" + model.Email + ".jpg";
                        await file.SaveAsAsync(filePath);

                    }
                }

                HttpContext.Session.Remove("PatientId");
                return RedirectToAction("ModifyPatientPage");


            }

            return RedirectToAction("ModifyPatientPage");


        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteQuery(IEnumerable<int> QueriesToDeleteCheckboxes)
        {

            if (QueriesToDeleteCheckboxes.Count<int>() != 0)
            {
                GetQueries mP = new GetQueries(_context);


                foreach (var p in QueriesToDeleteCheckboxes)
                {
                    await mP.deleteQuery(p);

                }


            }

            return RedirectToAction("ViewQueriesPage");


        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> DeletePhoto()
        {

            ModifyPatient m = new ModifyPatient(_context);
           await  m.deletePatientPhoto(int.Parse(HttpContext.Session.GetString("PatientId")),_hostingEnvironment);
            

            return RedirectToAction("EditPatientPage");


        }

        
        [HttpGet]
        [AllowAnonymous]
        public IActionResult EditPatientPage(string editPatient)
        {
            if(editPatient==null)
                editPatient = HttpContext.Session.GetString("PatientId");


            GetPatient model = new GetPatient(_context);
            Patient pa = model.getPatient(int.Parse(editPatient));
            PatientViewModel p = new PatientViewModel();
            p.Address = pa.Address;
            p.BloodGroup = pa.BloodGroup;
            p.Comments = pa.Comment;
            p.ContactNo = pa.Contact;
            p.DoctorDiagnosis = pa.Diagnosis;
            p.Email = pa.Email;
            p.Fname = pa.Fname;
            p.Gender = pa.Gender;
            p.Lname = pa.Lname;
            p.PatientAge = pa.Age;
            p.PatientDetails = pa.Detail;
            p.PatientHistory = pa.History;
            p.ProfilePicture = pa.ProfilePicture;

            HttpContext.Session.SetString("PatientId",editPatient);



            return View(p);

        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult ViewQueriesPage()
        {
            GetQueries getAllQ = new GetQueries(_context);
            

            return View(getAllQ.getAllQueries());

        }


    }
}

src/HospitalManagement/Controllers/DoctorsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using HospitalManagement.Models;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Http;
using System.Collections.Generic;
using HospitalManagement.ViewModels.Admin;
using Microsoft.Extensions.PlatformAbstractions;
using Microsoft.Net.Http.Headers;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace HospitalManagement.Controllers
{
    public class DoctorsController : Controller
    {
        private ApplicationDbContext _context;
        private IApplicationEnvironment _hostingEnvironment;


        public DoctorsController(ApplicationDbContext context, IApplicationEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;

        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult Home()
        {
            User user = new User();
            user.Email = HttpContext.Session.GetString("Email");
            user.Fname = HttpContext.Session.GetString("FName");

            return View(user);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult EditPatientPage()
        {
            GetPatient getPatient = new GetPatient(_context);
            List<Patient> patients = getPatient.getAllPatients();


            return View(patients);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult EditPatient(string editPatient)
        {
            if (editPatient == null)
                editPatient = HttpContext.Session.GetString("PatientId");


            GetPatient model = new GetPatient(_context);
            Patient pa = model.getPatient(int.Parse(editPatient));
            PatientViewModel p = new PatientViewModel();
            p.Address = pa.Address;
            p.BloodGroup = pa.BloodGroup;
            p.Comments = pa.Comment;
            p.ContactNo = pa.Contact;
            p.DoctorDiagnosis = pa.Diagnosis;
            p.Email = pa.Email;
            p.Fname = pa.Fname;
            p.Gender = pa.Gender;
            p.Lname = pa.Lname;
            p.PatientAge = pa.Age;
            p.PatientDetails = pa.Detail;
            p.PatientHistory = pa.History;
            p.ProfilePicture = pa.ProfilePicture;

            HttpContext.Session.SetString("PatientId", editPatient);



            return View(p);

        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SavePatientChanges(PatientViewModel model, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                ModifyPatient m = new ModifyPatient(_context);
                int count = 0;
                if (file != null)
                    count = 1;

                await m.updatePatient(int.Parse(HttpContext.Session.GetString("PatientId")), model, count);

                if (file != null)
                {
                    var fullPath = _hostingEnvironment.ApplicationBasePath + "\\wwwroot\\profiledat\\" + model.Email + ".jpg";
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }


                    var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                    if (fileName.EndsWith(".jpg") || fileName.EndsWith(".png") || fileName.EndsWith(".jpeg") || fileName.EndsWith(".gif") || fileName.EndsWith(".bmp") || fileName.EndsWith(".tiff"))

                    {

                        var filePath = _hostingEnvironment.ApplicationBasePath + "\\wwwroot\\profiledat\\" + model.Email + ".jpg";
                        await file.SaveAsAsync(filePath);

                    }
                }

                HttpContext.Session.Remove("PatientId");
                return RedirectToAction("EditPatientPage");


            }

            return RedirectToAction("EditPatientPage");


        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult HistoryPage()
        {
            GetPatient getPatient = new GetPatient(_context);
            List<Patient> patients = getPatient.getAllPatients();


            return View(patients);
        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ContactAdminPage()
        {


            return View();
        }



        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AskConfirm(string question)
        {

            ManageQueries m = new ManageQueries(_context);
           await m.addQuery(question, HttpContext.Session.GetString("Email"));



            return View();

        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult SearchPatientPage()
        {
            GetPatient getPatient = new GetPatient(_context);
            List<Patient> patients = getPatient.getAllPatients();


            return View(patients);
        }

        [HttpGet]
        public JsonResult GetPatients(string PatientName,string PatientAge, string PatientGender,string SortBy, string Order)
        {

            GetPatient getPatients = new GetPatient(_context);
            List<Patient> patients = new List<Patient>();


            if (PatientName == null && PatientAge == null && PatientGender == "Select")
            {
                patients = getPatients.getAllPatients();

            }
            else if (PatientName != null && PatientAge == null && PatientGender == "Select")
            {
                patients = getPatients.getPatientByName(PatientName);
            }
            else if (PatientName == null && PatientAge != null && PatientGender == "Select")
            {
                patients = getPatients.getPatientByAge(int.Parse(PatientAge));

            }
            else if (PatientName == null && PatientAge == null && PatientGender != "Select")
            {
                patients = getPatients.getPatientByGender(PatientGender);

            }

            else if (PatientName != null && PatientAge != null && PatientGender == "Select")
            {
                patients = getPatients.getPatientByNameAndAge(PatientName,int.Parse(PatientAge));

            }
            else if (PatientName != null && PatientAge == null && PatientGender != "Select")
            {
                patients = getPatients.getPatientByNameAndGender(PatientName, PatientGender);

            }
            else if (PatientName == null && PatientAge != null && PatientGender != "Select")
            {
                patients = getPatients.getPatientByAgeAndGender(int.Parse(PatientAge), PatientGender);

            }
            else if (PatientName != null && PatientAge != null && PatientGender != "Select")
            {
                patients = getPatients.getPatientByNameAgeAndGender(PatientName,int.Parse(PatientAge), PatientGender);

            }


            //sorting
            if (SortBy == "Fname")
            {
                if(Order== "Ascending")
                patients = patients.OrderBy(o => o.Fname).ToList();
                else
                    patients = patients.OrderByDescending(o => o.Fname).ToList();
            }
            else if (SortBy == "Lname")
            {

                if (Order == "Ascending")
                    patients = patients.OrderBy(o => o.Lname).ToList();
                else
                    patients = patients.OrderByDescending(o => o.Lname).ToList();

            }

            else if (SortBy == "Age")
            {
                if (Order == "Ascending")
                    patients = patients.OrderBy(o => o.Age).ToList();
                else
                    patients = patients.OrderByDescending(o => o.Age).ToList();
            }

            else if (SortBy == "Gender")
            {
                if (Order == "Ascending")
                    patients = patients.OrderBy(o => o.Gender).ToList();
                else
                    patients = patients.OrderByDescending(o => o.Gender).ToList();

            }



           
                

            return Json(patients);


        }


        // GET: Doctors
        public IActionResult Index()
        {
            return View(_context.Doctor.ToList());
        }

        // GET: Doctors/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Doctor doctor = _context.Doctor.Single(m => m.DoctorId == id);
            if (doctor == null)
            {
                return HttpNotFound();
            }

            return View(doctor);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
             
        }

        // POST: Doctors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                _context.Doctor.Add(doctor);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Doctor doctor = _context.Doctor.Single(m => m.DoctorId == id);
            if (doctor == null)
            {

src/HospitalManagement/Views/Doctors/AskConfirm.cshtml
@{
    ViewData["Title"] = "Confirmation";

}

<h2>Ask Admin</h2>

<div class="emailCon row">

    <div class="col-sm-12">
       Your query has been submitted!
    </div>

</div>


src/HospitalManagement/Views/Doctors/ContactAdminPage.cshtml

@{
    ViewData["Title"] = "Contact Admin";

}

<h2>@ViewData["Title"]</h2>


<div class="row adminP">
    <div class="col-sm-3">
    </div>

    <div class="askAdminPage col-sm-6">
        <form asp-controller="Doctors" asp-action="AskConfirm" method="post" autocomplete="on" role="form">

            <div class="centered">
                <h3 >Having problem? Ask Admin.</h3>
            </div>

            <br />


            <div class="Askinnerdiv">



                <div class="form-group">


                    <textarea  id="question" name="question" class="form-control text" placeholder="Enter your question here.." rows="8" style="max-width:500px;" required></textarea>
                </div>

                <div class="centered" >

                    <input type="submit"  class="btn btn-success btn-lg text" style="width:700px" value="Submit" />
                </div>


                </div>


        </form>





    </div>

    <div class="col-sm-3">
    </div>


</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/HospitalManagement/Views/Doctors/Delete.cshtml
@model HospitalManagement.Models.Doctor

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.about)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.about)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.contact)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.contact)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.country)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.fname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.lname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.lname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/HospitalManagement/Views/Doctors/EditPatient.cshtml
@model HospitalManagement.ViewModels.Admin.PatientViewModel

@{
    ViewData["Title"] = "Edit Patient";

}

<h2 class="header2" style="color:#022e4e;">Edit Patient Details</h2>


<p class="text-primary text">

    Update the patient record and Click the save changes button below

</p>


<div class="row">
    <div class="col-sm-5">
    </div>


    <div class="signPage col-sm-7">
        <form id="AddPatientForm" asp-controller="Doctors" asp-action="SavePatientChanges" method="post" autocomplete="on" role="form" enctype="multipart/form-data">



            <div style="padding-left:4%;">


                <div class="profile-header-container">
                    <div class="profile-header-img">


                        @if (@Model.ProfilePicture == null)
                        {
                            <img class="img-circle" src="http://www.iconshock.com/img_jpg/IMPRESSIONS/medical/jpg/256/patient_icon.jpg" />

                        }
                        else
                        {
                            <img class="img-circle" src="~/profiledat/@Html.Encode(@Model.ProfilePicture)" />
                        }





                    </div>
                </div>


            </div>



            <div style="padding-left:4%; padding-bottom:20px">

                <input type="file" name="file" id="file" class="filestyle text btn" data-classButton="btn btn-primary" data-input="false" data-classIcon="icon-plus" data-buttonText="Update Profile Picture" accept="image/*" />
                <br />
                <input type="button" class="btn btn-danger  text " value="Delete Picture" onclick="location.href='@Url.Action("DeletePhoto", "Admin")'" />


            </div>



            <div style="padding-left:4%;">


                <div class="row">

                    <div class="col-sm-6">
                        <label asp-for="Fname" class="text">First Name</label><span class="asteristik">*</span>
                        <input asp-for="Fname" id="Fname" type="text" class="form-control" placeholder="Enter First Name" onkeypress="return checkAlphabets(event)" />
                        <span asp-validation-for="Fname" id="patientCheckSpan" class="text-danger"></span>

                    </div>
                    <div class="col-sm-6">
                        <label asp-for="Lname" class="text">Last Name</label><span class="asteristik">*</span>
                        <input asp-for="Lname" id="Lname" type="text" class="form-control" placeholder="Enter Last Name" onkeypress="return checkAlphabets(event)" />
                        <span asp-validation-for="Lname" id="patientCheckSpan" class="text-danger"></span>

                    </div>

                </div>


                <br />

                <div class="form-group">
                    <label asp-for="Email" class="text">Patient's email address</label><span class="asteristik">*</span>
                    <input asp-for="Email" id="Email" type="email" class="form-control" placeholder="Enter email" />
                    <span asp-validation-for="Email" id="patientCheckSpan" class="text-danger"></span>

                </div>



                <div class="form-group ">

                    <label asp-for="Gender" class="text">Select gender</label><span class="asteristik">*</span>


                    <select asp-for="Gender" class="form-control text" style="color:#052483">
                        <option value="male" class="text">Male</option>
                        <option value="female" class="text">Female</option>

                    </select>
                    <span asp-validation-for="Gender" id="patientCheckSpan" class="text-danger"></span>

                </div>



                <div class="form-group">

                    <label asp-for="PatientAge" class="text">Patient's age</label><span class="asteristik">*</span>
                    <input asp-for="PatientAge" id="Age" class="form-control " type="number" onkeypress="return checkNumbers(event)" />
                    <span asp-validation-for="PatientAge" id="patientCheckSpan" class="text-danger"></span>

                </div>


                <div class="form-group">

                    <label asp-for="BloodGroup" class="text">Patient's Blood Group</label><span class="asteristik">*</span>
                    <select asp-for="BloodGroup" id="BloodGroup" class="form-control text" style="color:#052483">

                        <option value="select" class="text">Select blood group</option>

                        <option value="o+" class="text">O+</option>
                        <option value="o-" class="text">O-</option>

                        <option value="a+" class="text">A+</option>
                        <option value="a-" class="text">A-</option>

                        <option value="b+" class="text">B+</option>
                        <option value="b-" class="text">B-</option>

                        <option value="ab+" class="text">AB+</option>
                        <option value="ab-" class="text">AB-</option>



                    </select>
                    <span asp-validation-for="BloodGroup" id="patientCheckSpan" class="text-danger"></span>

                </div>




                <div class="form-group">

                    <label asp-for="ContactNo" class="text">Contact No</label>

                    <input asp-for="ContactNo" id="ContactNo" class="form-control " placeholder="Contact number" type="tel" onkeypress="return checkNumbers(event)" />

                </div>





                <div class="form-group">

                    <label asp-for="Address" class="text">Patient's address</label>

                    <textarea asp-for="Address" id="Address" class="form-control " placeholder="Address" rows="3" style="max-width:620px;"></textarea>
                </div>


                <br />

                <div class="form-group">

                    <label asp-for="PatientDetails" class="text">Patient's details</label>

                    <textarea asp-for="PatientDetails" id="PatientDetails" class="form-control " placeholder="Details.." rows="3" style="max-width:620px;"></textarea>
                </div>


                <br />


                <div class="form-group">

                    <label asp-for="PatientHistory" class="text">Patient's history</label>

                    <textarea asp-for="PatientHistory" id="PatientHistory" class="form-control " placeholder="History of diseases" rows="2" style="max-width:620px;"></textarea>
                </div>


                <br />

                <div class="form-group">

                    <label asp-for="DoctorDiagnosis" class="text">Doctor's diagnosis</label>

                    <textarea asp-for="DoctorDiagnosis" id="DoctorDiagnosis" class="form-control " placeholder="Diagnosis of diseases" rows="2" style="max-width:620px;"></textarea>
                </div>


                <br />


                <div class="form-group">

                    <label asp-for="Comments" class="text">Comments</label>

                    <textarea asp-for="Comments" id="Comments" class="form-control " placeholder="Comments about the patient" rows="2" style="max-width:620px;"></textarea>
                </div>


                <br />

                <br />


                <div class="row">
                    <div class="col-sm-3">
                    </div>

                    <input type="submit" class="btn btn-primary btn-large btn-block text col-sm-9" value="Save Changes" style="margin:auto; height:50px;" />
                </div>

            </div>

        </form>

    </div>

</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/HospitalManagement/Views/Doctors/Home.cshtml
@model User

@{
    ViewData["Title"] = "Home";

}

<h2>@ViewData["Title"]</h2>

<h3>Welcome @Model.Fname</h3>

<div class="row">
    <div class="col-sm-3">
    </div>

    <div class="col-sm-5">

        <div class="form-group">

            <input type="button" class="btn btn-primary btn-lg text "  style="width:300px; " value="View Patient's History" onclick="location.href='@Url.Action("HistoryPage", "Doctors")'"  >
        
        </div>

        <div class="form-group">

            <input type="button" class="btn btn-primary btn-lg text  " style="width:300px; "  value="Edit Patient's Data" onclick="location.href='@Url.Action("EditPatientPage", "Doctors")'">
        </div>

      

        <div class="form-group">

            <input type="button" class="btn btn-primary btn-lg text " style="width:300px; " value="Contact Admin" onclick="location.href='@Url.Action("ContactAdminPage", "Doctors")'">
        </div>

        <div class="form-group">

            <input type="button" class="btn btn-primary btn-lg text  " style="width:300px; " value="Search Patient" onclick="location.href='@Url.Action("SearchPatientPage", "Doctors")'">
        </div>

        </div>

    <div class="col-sm-4">
    </div>


</div>
